<?php
/**
 * Bootstrap WordPress Configuration
 *
 * @package WPStarter
 */

/**
 * Do not edit this file.
 */
require_once dirname( __DIR__ ) . '/vendor/autoload.php';
require_once dirname( __DIR__ ) . '/config/app.php';
/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
